blueprint:
  name: Actions for Bitron Video AV2010/23 remote device
  description: When a button is pressed, the defined actions will be executed.
  domain: automation
  source_url: https://raw.githubusercontent.com/heidrich76/home_assistant_custom/main/blueprints/automation/bitron_av201023_remote.yaml
  input:
    remote:
      name: Bitron Video remote
      description: Please select Bitron Video remote device.
      selector:
        entity:
          domain:
            - sensor
          multiple: false
    action_1:
      name: 1 Point / Brightness Step Up
      description: Action for 1 Point / Brightness Step Up
      default: []
      selector:
        action: {}
    action_2:
      name: 2 Points / On
      description: Action for 2 Points / On
      default: []
      selector:
        action: {}
    action_3:
      name: 3 Points / Off
      description: Action for 3 Points / Off
      default: []
      selector:
        action: {}
    action_4:
      name: 4 Points / Brightness Step Down
      description: Action for 4 Points / Brightness Step Down
      default: []
      selector:
        action: {}
trigger:
  - platform: state
    entity_id:
      - !input remote
condition: []
action:
  - choose:
      - conditions: "{{ trigger.to_state.state == 'brightness_step_up' }}"
        sequence: !input action_1
      - conditions: "{{ trigger.to_state.state == 'on' }}"
        sequence: !input action_2
      - conditions: "{{ trigger.to_state.state == 'off' }}"
        sequence: !input action_3
      - conditions: "{{ trigger.to_state.state == 'brightness_step_down' }}"
        sequence: !input action_4
mode: parallel
max: 10
