blueprint:
  name: Actions for TuYa TS0215A remote (MQTT Device Trigger)
  description: Executes defined actions when MQTT device triggers from TuYa TS0215A are received.
  domain: automation
  input:
    remote_device:
      name: MQTT Device
      description: Choose the MQTT device representing the TuYa remote.
      selector:
        device: {}
    action_1:
      name: Button A / Arm Day Zones
      description: Action for Button A / Arm Day Zones
      default: []
      selector:
        action: {}
    action_2:
      name: Button B / Disarm
      description: Action for Button B / Disarm
      default: []
      selector:
        action: {}
    action_3:
      name: Button 0 / SOS / Emergency
      description: Action for Button 0 / SOS / Emergency
      default: []
      selector:
        action: {}
    action_4:
      name: Button 1 / Arm All Zones
      description: Action for Button 1 / Arm All Zones
      default: []
      selector:
        action: {}

trigger:
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: arm_day_zones
    id: arm_day
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: disarm
    id: disarm
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: emergency
    id: emergency
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: arm_all_zones
    id: arm_all

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: arm_day
        sequence: !input action_1
      - conditions:
          - condition: trigger
            id: disarm
        sequence: !input action_2
      - conditions:
          - condition: trigger
            id: emergency
        sequence: !input action_3
      - conditions:
          - condition: trigger
            id: arm_all
        sequence: !input action_4

mode: parallel
max: 10
